name: Docker Image CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f smartmovefront-container || true
    - name: Pull Docker image
      run: sudo docker pull mattdv57/smartmovefront:latest
    - name: Run Docker container
      run: sudo docker run -d -p 8080:8080 --name smartmovefront-container mattdv57/smartmovefront

