name: Docker Image CD
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f smartmovefront-container || true
    - name: Pull Docker image
      run: sudo docker pull mattdv57/smartmovefront:latest
    - name: Run Docker container
      run: sudo docker run -d -p 443:443 -e VITE_API_URL_BACKEND="${{ secrets.VITE_API_URL_BACKEND }}" --name smartmovefront-container mattdv57/smartmovefront

