name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull mattdv57/smartmovefront:latest
    - name: Delete Old docker container
      run: sudo docker rm -f smartmovefront-container || true
    - name: Run Docker container
      run: sudo docker run -d --name smartmovefront-container mattdv57/smartmovefront
