name: Docker Image CI

run-name: ${{ github.actor }} is doing CI using GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: NodeJS
      - name: Install Node
        run: | 
            sudo apt install nodejs -y
            sudo apt install npm -y

      # Step 3: Run NPM install
      - name: Run NPM install
        run: npm install -y

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Kill port 3000
        run: npx kill-port 3000

      - name: Start front
        run: nohup npm start &
  
        # Ejecución 1 del test WrongFile
      - name: Run test Wrong file
        id: test_wrong_file
        run: |
          CI=true npm run test:userWrongFile || echo "failure" > result.txt
        continue-on-error: true  # Permite que continúe si falla
  
      - name: Show logs Wrong file
        run: cat ./logsWrongFile.txt

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: mattdv57/smartmovefront:latest

    
