name: Docker Image CI

run-name: ${{ github.actor }} is doing CI using GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
            docker build \
            -t mattdv57/smartmovefront \
            --build-arg VITE_API_URL_BACKEND='${{ secrets.VITE_API_URL_BACKEND }}' .

            docker tag smartmovefront mattdv57/smartmovefront:latest

            docker push mattdv57/smartmovefront:latest




    
